# Generated by Django 4.0.4 on 2022-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='card_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
